---
- name: Deploy Apache Web Server with Custom Index Page using Ansible
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Start Service httpd
      ansible.builtin.service:
        name: apache2
        state: started
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
    - name: Create /var/www/html directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: "0755"
    - name: Get index.html
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/dpakGit/My_Ansible/main/ansibledemo/index.html
        dest: /var/www/html/index.html
        mode: "0644"
